using UnityEngine;

// SCRIPT GENERATED BY CHAT GPT 4o
public class BloodParticleDecalSpawner : MonoBehaviour
{
	private float decalSpawnChance = 0.05f;

	private ParticleSystem ps;
	private ParticleSystem.Particle[] particles;

	void Awake()
	{
		ps = GetComponent<ParticleSystem>();
		particles = new ParticleSystem.Particle[ps.main.maxParticles];
	}

	void LateUpdate()
	{
		int particleCount = ps.GetParticles(particles);

		for (int i = 0; i < particleCount; i++)
		{
			// Check if the particle is near the end of its lifetime
			if (particles[i].remainingLifetime <= Time.deltaTime)
			{
				// Decide to spawn a decal based on chance
				if (Random.value <= decalSpawnChance)
				{
					Vector3 spawnPosition = particles[i].position;

					// Spawn the blood decal
					BloodPoolSpawner.SpawnBloodPool(spawnPosition, BloodPoolSpawner.BloodPoolSize.SMALL);
				}
			}
		}

		// Update particles back into the system (required after modifying particle data)
		ps.SetParticles(particles, particleCount);
	}
}
